# Generated by Django 5.1.2 on 2024-10-18 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('sa', 'Salt'), ('sw', 'Sweet')], max_length=2)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderName', models.CharField(max_length=40, null=True)),
                ('amount', models.IntegerField()),
                ('orderType', models.CharField(choices=[('tg', 'To go'), ('fh', 'For here')], max_length=2)),
                ('status', models.CharField(choices=[('oh', 'On hold'), ('op', 'On preparation'), ('se', 'Served')], default='oh', max_length=2)),
                ('date', models.DateField(auto_now=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.product')),
            ],
        ),
    ]
